l_polish:
 adulterer_difficulty: "Je [GetTrait('adulterer').GetName( GetNullCharacter )]"
 adventurer_interesting_desc: "Je dobrodruh"
 albino_difficulty: "Je [GetTrait('albino').GetName( GetNullCharacter )]"
 albino_interesting_desc: "Je [GetTrait('albino').GetName( GetNullCharacter )]"
 at_war_difficulty: "Ve válce"
 bad_genetics_desc: "Špatné genetické rysy"
 bastard_difficulty: "Je [GetTrait('bastard').GetName( GetNullCharacter )]"
 beauty_bad_1_difficulty: "Je [GetTrait('beauty_bad_1').GetName( GetNullCharacter )]"
 beauty_bad_2_difficulty: "Je [GetTrait('beauty_bad_2').GetName( GetNullCharacter )]"
 beauty_bad_3_difficulty: "Je [GetTrait('beauty_bad_3').GetName( GetNullCharacter )]"
 beauty_good_1_difficulty: "Je [GetTrait('beauty_good_1').GetName( GetNullCharacter )]"
 beauty_good_2_difficulty: "Je [GetTrait('beauty_good_2').GetName( GetNullCharacter )]"
 beauty_good_3_difficulty: "Je [GetTrait('beauty_good_3').GetName( GetNullCharacter )]"
 beloved_by_pope_interesting_desc: "Oblíbený papežem"
 berserker_interesting_desc: "Je [GetTrait('berserker').GetName( GetNullCharacter )]"
 blademaster_xp_desc: "Zkušený [GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )]"
 bleeder_difficulty: "Je [GetTrait('bleeder').GetName( GetNullCharacter )]"
 blind_difficulty: "Je [GetTrait('blind').GetName( GetNullCharacter )]"
 blind_interesting_desc: "Je [GetTrait('blind').GetName( GetNullCharacter )]"
 blood_of_prophet_interesting_desc: "Má [GetTrait('blood_of_prophet').GetName( GetNullCharacter )]"
 born_in_the_purple_interesting_desc: "Je [GetTrait('born_in_the_purple').GetName( GetNullCharacter )]"
 brazen_commander_interesting_desc: "Je bezohledný velitel"
 can_feudalize_interesting_desc: "Může feudalizovat"
 cannibal_difficulty: "Je [GetTrait('cannibal').GetName( GetNullCharacter )]"
 celibate_difficulty: "Je [GetTrait('celibate').GetName( GetNullCharacter )]"
 character_difficulty_breakdown_header: "Rozpis obtížnosti"
 character_difficulty_text: "Obtížnost: [Character.Custom('CharacterDifficulty')]"
 character_interest_breakdown_header: "Zajímavé aspekty"
 child_of_destiny_desc: "Je dítě osudu"
 children_wrong_dynasty_difficulty: "Děti jsou z jiné dynastie"
 choose_destiny_header_text: "Vyberte nový osud"
 clubfooted_difficulty: "Je [GetTrait('clubfooted').GetName( GetNullCharacter )]"
 comfort_eater_difficulty: "Je [GetTrait('comfort_eater').GetName( GetNullCharacter )]"
 craven_difficulty: "Je [GetTrait('craven').GetName( GetNullCharacter )]"
 crusader_king_interesting_desc: "Je [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 debt_level_difficulty: "Vysoká úroveň dluhů"
 decadent_difficulty: "Je [GetTrait('decadent').GetName( GetNullCharacter )]"
 denounced_difficulty: "Je [GetTrait('denounced').GetName( GetNullCharacter )]"
 depressed_difficulty: "Je [GetTrait('depressed').GetName( GetNullCharacter )]"
 deviant_difficulty: "Je [GetTrait('deviant').GetName( GetNullCharacter )]"
 devoted_interesting_desc: "Je [GetTrait('devoted').GetName( GetNullCharacter )]"
 different_faith_interesting_desc: "Je jiné víry"
 different_government_desc: "Má jiné zřízení"
 disfigured_difficulty: "Je [GetTrait('disfigured').GetName( GetNullCharacter )]"
 disinherited_difficulty: "Je [GetTrait('disinherited').GetName( GetNullCharacter )]"
 disinherited_interesting_desc: "Je [GetTrait('disinherited').GetName( GetNullCharacter )]"
 disloyal_interesting_desc: "Je [GetTrait('disloyal').GetName( GetNullCharacter )]"
 drunkard_difficulty: "Je [GetTrait('drunkard').GetName( GetNullCharacter )]"
 dull_difficulty: "Je [GetTrait('dull').GetName( GetNullCharacter )]"
 dwarf_difficulty: "Je [GetTrait('dwarf').GetName( GetNullCharacter )]"
 dwarf_interesting_desc: "Je [GetTrait('dwarf').GetName( GetNullCharacter )]"
 elder_difficulty: "Pokročilý věk"
 eunuch_difficulty: "Je [GetTrait('eunuch_1').GetName( GetNullCharacter )]"
 excommunicated_difficulty: "Je exkomunikován"
 extremely_wealthy_interesting_desc: "Velmi bohatý"
 faction_difficulty: "Je cílem mocných frakcí"
 faith_warrior_interesting_desc: "Je [GetTrait('faith_warrior').GetName( GetNullCharacter )]"
 flagellant_difficulty: "Je [GetTrait('flagellant').GetName( GetNullCharacter )]"
 fornicator_difficulty: "Je [GetTrait('fornicator').GetName( GetNullCharacter )]"
 giant_difficulty: "Je [GetTrait('giant').GetName( GetNullCharacter )]"
 giant_interesting_desc: "Je [GetTrait('giant').GetName( GetNullCharacter )]"
 gluttonous_difficulty: "Je [GetTrait('gluttonous').GetName( GetNullCharacter )]"
 gold_difficulty: "Nadměrné bohatství"
 good_genetics_desc: "Dobré genetické rysy"
 gout_difficulty: "Má [GetTrait('gout_ridden').GetName( GetNullCharacter )]"
 greedy_steward_interesting_desc: "Je chamtivý správce"
 has_a_legend_interesting_desc: "Má legendu"
 has_both_good_and_bad_genetics_desc: "Má jak dobré, tak špatné genetické rysy"
 has_historical_artifacts_interesting_desc: "Vlastní unikátní historické artefakty"
 has_interesting_story_desc: "Má zajímavý příběh"
 has_many_bad_relations_desc: "Je obklopen rivaly"
 has_many_good_relations_desc: "Má mnoho přátel"
 has_nickname_desc: "Má přezdívku"
 has_secrets_interesting_desc: "Má tajemství"
 hashishiyah_difficulty: "Je [GetTrait('hashishiyah').GetName( GetNullCharacter )]"
 head_of_faith_interesting_desc: "Je hlavou víry"
 herbalist_xp_desc: "Zkušený [GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )]"
 high_diplomacy_desc: "Má vysokou diplomacii"
 high_education_desc: "Je vysoce vzdělaný"
 high_intrigue_desc: "Má vysoké schopnosti intrik"
 high_learning_desc: "Má vysoké vzdělání"
 high_martial_desc: "Má vysoké válečné schopnosti"
 high_prowess_desc: "Má vysokou bojovou zdatnost"
 high_skills_desc: "Dovednosti jsou velmi vysoké"
 high_stewardship_desc: "Má vysoké schopnosti správy"
 higher_title_desc: "Drží vyšší titul"
 holds_baghdad_interesting_desc: "Drží [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_byzantion_interesting_desc: "Drží [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Drží [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Drží [GetTitleByKey('c_mecca').GetBaseName]"
 holds_rome_interesting_desc: "Drží [GetTitleByKey('c_roma').GetBaseName]"
 holds_special_buildings_interesting_desc: "Ovládá speciální budovy"
 holy_site_steward_interesting_desc: "Hlavní město je svaté místo"
 hostile_faith_liege_difficulty: "Lenní pán nepřátelské víry"
 hunchbacked_difficulty: "Je [GetTrait('hunchbacked').GetName( GetNullCharacter )]"
 hunter_xp_desc: "Zkušený [GetTrait('lifestyle_hunter').GetName( GetNullCharacter )]"
 imprisoned_difficulty: "Je vězněn"
 improvident_difficulty: "Je [GetTrait('improvident').GetName( GetNullCharacter )]"
 inappetetic_difficulty: "Je [GetTrait('inappetetic').GetName( GetNullCharacter )]"
 inbred_difficulty: "Je [GetTrait('inbred').GetName( GetNullCharacter )]"
 incapable_difficulty: "Je [GetTrait('incapable').GetName( GetNullCharacter )]"
 incestuous_difficulty: "Je [GetTrait('incestuous').GetName( GetNullCharacter )]"
 infertile_difficulty: "Je [GetTrait('infertile').GetName( GetNullCharacter )]"
 infirm_difficulty: "Je [GetTrait('infirm').GetName( GetNullCharacter )]"
 inheritance_line_desc: "Je v linii dědictví"
 intellect_bad_1_difficulty: "Je [GetTrait('intellect_bad_1').GetName( GetNullCharacter )]"
 intellect_bad_2_difficulty: "Je [GetTrait('intellect_bad_2').GetName( GetNullCharacter )]"
 intellect_bad_3_difficulty: "Je [GetTrait('intellect_bad_3').GetName( GetNullCharacter )]"
 intellect_good_1_difficulty: "Je [GetTrait('intellect_good_1').GetName( GetNullCharacter )]"
 intellect_good_2_difficulty: "Je [GetTrait('intellect_good_2').GetName( GetNullCharacter )]"
 intellect_good_3_difficulty: "Je [GetTrait('intellect_good_3').GetName( GetNullCharacter )]"
 irritable_difficulty: "Je [GetTrait('irritable').GetName( GetNullCharacter )]"
 is_a_vassal_difficulty: "Je vazalem"
 is_diarch_interesting_desc: "Je diarcha"
 is_ill_difficulty: "Trpí oslabující nemocí"
 is_your_child_desc: "Je vaše dítě"
 is_your_close_family_desc: "Je z vaší blízké rodiny"
 is_your_house_desc: "Je z vaší dynastie"
 killed_a_lot_interesting_desc: "Zabil více než 10 lidí"
 kind_hearted_diplomat_interesting_desc: "Je dobrosrdečný diplomat"
 kinslayer_difficulty: "Je [GetTrait('kinslayer_1').GetName( GetNullCharacter )]"
 knows_many_secrets_interesting_desc: "Zná mnoho tajemství"
 landed_heir_desc: "Má dědice s tituly"
 landed_spouse_desc: "Má manžela/manželku s tituly"
 landless_heir_uninteresting_desc: "Dědic bez panství"
 lazy_difficulty: "Je [GetTrait('lazy').GetName( GetNullCharacter )]"
 legitimacy_difficulty: "Z legitimity"
 legitimacy_interesting_desc: "Velmi legitimní vládce"
 leper_difficulty: "Je [GetTrait('leper').GetName( GetNullCharacter )]"
 liege_crusader_king_liege_lineage_interesting_desc: "Lenní pán linie [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 lisping_difficulty: "Má [GetTrait('lisping').GetName( GetNullCharacter )] problém s mluvou"
 losing_war_difficulty: "Prohrává války"
 lovers_pox_difficulty: "Má [GetTrait('lovers_pox').GetName( GetNullCharacter )]"
 loyal_interesting_desc: "Je [GetTrait('loyal').GetName( GetNullCharacter )]"
 lunatic_difficulty: "Je [GetTrait('lunatic').GetName( GetNullCharacter )]"
 maimed_difficulty: "Je [GetTrait('maimed').GetName( GetNullCharacter )]"
 military_difficulty: "Vojenská síla"
 more_beautiful_desc: "Je krásnější než dědic"
 more_famous_desc: "Je slavnější než dědic"
 more_fit_desc: "Je zdatnější než dědic"
 more_skillful_desc: "Je zručnější než dědic"
 more_smart_desc: "Je chytřejší než dědic"
 more_strong_desc: "Je silnější než dědic"
 multiduke_interesting_desc: "Drží mnoho vévodství"
 murderer_difficulty: "Je [GetTrait('murderer').GetName( GetNullCharacter )]"
 mystic_xp_desc: "Zkušenost jako [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]"
 new_liege_desc: "Byl by pod novým lenním pánem"
 new_top_liege_desc: "Byl by pod novým nejvyšším lenním pánem"
 non_adult_difficulty: "Dítě"
 non_dominant_gender_ambitious_char_interesting_desc: "Je ambiciózní osoba nedominantního pohlaví"
 non_dominant_gender_ruler_interesting_desc: "Je vládcem nedominantního pohlaví"
 nonpreferred_gender_difficulty: "Pohlaví v náboženství není preferováno"
 opposite_struggle_faction_desc: "Protichůdná frakce ve sporu"
 outside_realm_desc: "Nezávislý vládce"
 paranoid_difficulty: "Je [GetTrait('paranoid').GetName( GetNullCharacter )]"
 part_of_feud_desc: "Je součástí sporu"
 peasant_leader_interesting_desc: "Je [GetTrait('peasant_leader').GetName( GetNullCharacter )]"
 physician_xp_desc: "Zkušený [GetTrait('lifestyle_physician').GetName( GetNullCharacter )]"
 physique_bad_1_difficulty: "Je [GetTrait('physique_bad_1').GetName( GetNullCharacter )]"
 physique_bad_2_difficulty: "Je [GetTrait('physique_bad_2').GetName( GetNullCharacter )]"
 physique_bad_3_difficulty: "Je [GetTrait('physique_bad_3').GetName( GetNullCharacter )]"
 physique_good_1_difficulty: "Je [GetTrait('physique_good_1').GetName( GetNullCharacter )]"
 physique_good_2_difficulty: "Je [GetTrait('physique_good_2').GetName( GetNullCharacter )]"
 physique_good_3_difficulty: "Je [GetTrait('physique_good_3').GetName( GetNullCharacter )]"
 pious_theologian_interesting_desc: "Je zbožný teolog"
 poet_interesting_desc: "Je [GetTrait('lifestyle_poet').GetName( GetNullCharacter )]"
 poor_health_difficulty: "Špatný zdravotní stav"
 populist_leader_interesting_desc: "Je [GetTrait('populist_leader').GetName( GetNullCharacter )]"
 possessed_difficulty: "Je [GetTrait('possessed').GetName( GetNullCharacter )]"
 powerful_neighbors_difficulty: "Mocní sousední vládci"
 poxed_difficulty: "Má [GetTrait('great_pox').GetName( GetNullCharacter )]"
 pressed_claims_desc: "Má uplatněné nároky"
 primary_heir_wrong_dynasty_difficulty: "Hlavní dědic z jiné dynastie"
 profligate_difficulty: "Je [GetTrait('profligate').GetName( GetNullCharacter )]"
 pure_blooded_interesting_desc: "Je [GetTrait('pure_blooded').GetName( GetNullCharacter )]"
 rakish_difficulty: "Je [GetTrait('rakish').GetName( GetNullCharacter )]"
 reclusive_difficulty: "Je [GetTrait('reclusive').GetName( GetNullCharacter )]"
 reveler_xp_desc: "Zkušený [GetTrait('lifestyle_reveler').GetName( GetNullCharacter )]"
 rivals_difficulty: "Má rivaly"
 ruler_in_foreign_lands_interesting_desc: "Je vládcem v cizích zemích"
 salacious_seducer_interesting_desc: "Je smilný svůdce"
 scaly_difficulty: "Má [GetTrait('scaly').GetName( GetNullCharacter )] kůži"
 scaly_interesting_desc: "Má [GetTrait('scaly').GetName( GetNullCharacter )] kůži"
 second_in_line_desc: "Druhý v linii dědictví"
 severely_wounded_difficulty: "Je těžce zraněn"
 shrewd_difficulty: "Je [GetTrait('shrewd').GetName( GetNullCharacter )]"
 shy_difficulty: "Je [GetTrait('shy').GetName( GetNullCharacter )]"
 sickly_difficulty: "Je [GetTrait('sickly').GetName( GetNullCharacter )]"
 sinful_bastard_interesting_desc: "Je hříšný [GetTrait('bastard').GetName( GetNullCharacter )]"
 sinful_traits_difficulty: "Má hříšné rysy"
 skills_difficulty: "Z dovedností"
 small_king_interesting_desc: "Je vládcem malého království"
 sodomite_difficulty: "Je [GetTrait('sodomite').GetName( GetNullCharacter )]"
 spindly_difficulty: "Je [GetTrait('spindly').GetName( GetNullCharacter )]"
 stress_level_difficulty: "Vysoká úroveň stresu"
 strong_difficulty: "Je [GetTrait('strong').GetName( GetNullCharacter )]"
 strong_hook_liege_interesting_desc: "Má silný hák vůči lennímu pánovi"
 stronger_than_liege_interesting_desc: "Silnější než lenní pán"
 stuttering_difficulty: "Má [GetTrait('stuttering').GetName( GetNullCharacter )] problém s mluvou"
 tall_claims_desc: "Má významné nároky"
 three_sins_desc: "Má tři hříchy"
 three_virtues_desc: "Má tři ctnosti"
 tourney_xp_desc: "Zkušený [GetTrait('tourney_participant').GetName( GetNullCharacter )]"
 traveler_xp_desc: "Zkušený [GetTrait('lifestyle_traveler').GetName( GetNullCharacter )]"
 treacherous_schemer_interesting_desc: "Je zrádný intrikán"
 underrepresented_culture_interesting_desc: "Patří k málo zastoupené kultuře"
 underrepresented_faith_interesting_desc: "Patří k málo zastoupené víře"
 unlanded_difficulty: "Nemá žádné tituly"
 unpressed_claims_desc: "Má neuplatněné nároky"
 valiant_knight_interesting_desc: "Je udatný rytíř"
 varangian_interesting_desc: "Je [GetTrait('varangian').GetName( GetNullCharacter )]"
 virtues_interesting_desc: "Má ctnostné rysy"
 virtuous_traits_difficulty: "Má ctnostné rysy"
 weak_difficulty: "Je [GetTrait('weak').GetName( GetNullCharacter )]"
 weak_domain_difficulty: "Slabé panství"
 weak_heritage_difficulty: "Má slabé dědičné vlohy"
 weak_hook_liege_interesting_desc: "Má slabý hák vůči lennímu pánovi"
 wheezing_difficulty: "Je [GetTrait('wheezing').GetName( GetNullCharacter )]"
 will_become_adventurer: "Stane se [GetGovernment('landless_adventurer_government').GetName]"
 witch_difficulty: "Je [GetTrait('witch').GetName( GetNullCharacter )]"
 wounded_difficulty: "Je [GetTrait('wounded_1').GetName( GetNullCharacter )]"
 wrong_lineality_difficulty: "Nesprávná linie v manželství"
