l_polish:
 ALWAYS_HIDE: "Vždy skrýt"
 ALWAYS_SHOW: "Vždy zobrazit"
 BASED_ON_ZOOM_LEVEL: "Dynamické"
 FIVE_YEAR: "Každých 5 let"
 HALFYEAR: "Každých 6 měsíců"
 MONTHLY: "Každý měsíc"
 NEVER: "Nikdy"
 Norse: "@wrath_icon! Pánové severu"
 RESET_REACTIVE_ADVICE: "Obnovit reaktivní rady"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Opravdu chcete obnovit reaktivní rady?"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Obnovit reaktivní rady"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Obnovit reaktivní rady#!\nPředtím zobrazené reaktivní rady se znovu objeví."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Pokročilé – Obecné"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Pokročilé – Postavy"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Pokročilé – Mapa"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Obecné"
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Stahovatelný obsah"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Atmosféra"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portréty"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Různé"
 SETTINGS_CATEGORY_LANGUAGE: "Jazyk"
 SETTINGS_CATEGORY_MAP: "Mapa"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Ovládání mapy"
 SETTINGS_CATEGORY_MULTIPLAYER: "Více hráčů"
 SETTINGS_CATEGORY_SAVE_GAMES: "Uložené hry"
 SETTINGS_CATEGORY_SFX: "Specifické zvukové efekty"
 SETTINGS_CATEGORY_STYLING: "Styl rozhraní"
 SETTINGS_CATEGORY_TOOLTIPS: "Nápovědy"
 SETTINGS_CATEGORY_TUTORIAL: "Návod"
 SETTINGS_DISCARD_CHANGES: "Zrušit změny"
 SETTING_ADVANCED_SHADERS: "Pokročilé efekty shaderů"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Advanced Shader Effects\n#!Tato možnost zapne pokročilé efekty shaderů.\n\nVypnutí může zvýšit výkon na úkor horšího vzhledu některých efektů (např. terén a voda)."
 SETTING_Ambience: "Ambientní zvuky"
 SETTING_Ambience_TOOLTIP: "#T Ambience Volume\n#!Nastavuje hlasitost prostředí (ambientu)."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Pozadí postavy scény dvora"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nUrčuje, zda by 3D scéna Královského dvora měla zobrazovat méně důležité postavy na pozadí."
 SETTING_DEBUG_SAVES: "Number of debug saves"
 SETTING_DISABLED_HINTS: "Zakázané tipy"
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED: "Osvětlení papírové mapy"
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED_TOOLTIP: "#T $SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED$#!\nUrčuje, zda by papírová mapa měla přijímat osvětlení a stíny z mapového stolu. (vypněte toto pro klasické zbarvení papírové mapy)"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Pobřežní hranice"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nTato možnost ovládá, kdy by měly být zobrazeny pobřežní hranice panství.\nPokud je zvoleno $BASED_ON_ZOOM_LEVEL$, budou skryty v režimu detailního přiblížení.\n\nVýběr $ALWAYS_SHOW$ nebo $ALWAYS_HIDE$ může zvýšit výkon za cenu toho, že pobřežní hranice se nebudou skrývat dynamicky."
 SETTING_HUD_SKIN: "Vzhled rozhraní (HUD)"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nNastavuje vizuální motiv HUD rozhraní - 2D uživatelské rozhraní zobrazené na hlavní herní obrazovce.\n\nPokud je vybráno $hud_skin_auto$, HUD se změní podle kultury, víry a hlavního sídla hráčova panství."
 SETTING_MAP_HIGHLIGHT: "Zvýraznění kurzoru na mapě"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nUrčuje intenzitu zvýraznění kurzoru na mapě."
 SETTING_MAP_TABLE_STYLE: "Styl mapového stolu"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nNastavuje vizuální styl mapového stolu - mapy a 3D prostředí zobrazeného při oddálení.\n\nPokud je vybráno $map_table_style_auto$, bude styl mapového stolu vybrán podle aktuálního hráče a jeho postavy."
 SETTING_REACTIVE_TUTORIAL: "Zobrazovat reaktivní rady"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nUrčuje, zda má hra zobrazovat reaktivní rady reagující na způsob, jak hrajete. Užitečné pro nové hráče Crusader Kings III."
 SETTING_RESET_CAMERA_ROTATION: "Obnovení natočení kamery"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nUrčuje, zda by se měla kamera po otočení uživatelem automaticky vrátit do výchozí polohy."
 SETTING_RICH_PRESENCE: "Rich Presence"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nZobrazuje informace o vaší aktuální herní relaci vašim přátelům, pokud to vaše platforma podporuje."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Automatické panování kamery v královském dvoře"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nUrčuje, zda by se kamera v královském dvoře měla při nečinnosti jemně panovat přes dvůr.\n\nPokud jsou Animované postavy vypnuté, toto nastavení nemá vliv."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Hladké přechody kamery v královském dvoře"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nUrčuje, zda by se kamera v královském dvoře měla plynule přesouvat na nové místo.\n\nPokud jsou Animované postavy vypnuté, toto nastavení nemá vliv."
 SETTING_SHOW_CONTENT_SOURCE: "Zobrazit DLC události"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nUrčuje, zda události zobrazí, z jakého DLC pocházejí."
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Podrobné ikony [raid|E]"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nNastavuje, zda by se mapové ikony [raid|E] měly zobrazovat jako zjednodušené nebo podrobné\n\n#I Pokud je zapnuto, podržte Alt pro zobrazení všech držeb s kořistí, které můžete [raid|E].#!"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Zobrazit grafické nemoci a zranění"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nUrčuje, zda budou na portrétech postav viditelné grafické zranění a nemoci."
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Grafika nemocí"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nUrčuje, zda se mají na mapě zobrazovat efekty nemocí."
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Grafika legendy"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nUrčuje, zda se mají na mapě zobrazovat efekty legendy."
 SETTING_SHOW_NUDITY: "Zobrazit nahotu"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nUrčuje, zda mohou být postavy zobrazeny nazí."
 SETTING_SHOW_SUGGESTIONS: "Zobrazovat návrhy"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nUrčuje, zda má hra pravidelně navrhovat něco k udělání. Užitéčné pro nové hráče Crusader Kings III."
 SETTING_Sound_Effects: "Všechny zvukové efekty"
 SETTING_Sound_Effects_TOOLTIP: "#T Sound Effects Volume\n#!Nastavuje hlasitost VŠECH zvukových efektů."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Naklánění kamery při oddálení"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nUrčuje, zda by se měla kamera při oddalování naklánět směrem k výchozímu náklonu."
 SETTING_TOOLTIP_DELAY: "Zpoždění nápovědy"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nNastavuje zpoždění, než se zobrazí nápovědy."
 SETTING_TOOLTIP_LOCK_TIME: "Zpoždění zamknutí"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nNastavuje zpoždění před zamčením nápověd."
 SETTING_TOOLTIP_MODE: "Režim nápověd"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Zamknutí akcí"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nStiskněte #V Middle Mouse#! pro zamčení a odemčení nápověd."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Časové zamčení"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nNápovědy se zamknou, pokud se kurzor na chvíli nepohne. #weak (Výchozí nastavení.)#!"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Tendence myši"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nNápovědy se automaticky zamknou na místě, dokud kurzor neodjede pryč."
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nNastavuje způsob, jakým se nápovědy „zamykají“, umožňující nápovědy v nápovědách."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Zpoždění otevření, při již zamčené"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nNastavuje zpoždění před zamčením nápověd, když je již otevřená jiná nápověda."
 SETTING_TOOLTIP_UNLOCK_TIME: "Zpoždění odemčení"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nNastavuje zpoždění před odemčením nápověd."
 SETTING_TUTORIAL: "Návod"
 SETTING_USE_DYNASTY_NAMED_REALMS: "Panství pojmenovaná podle dynastie"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nNěkteré kultury pojmenují svůj primární titul podle dynastie (např. Abbásovci)."
 SETTING_WINTER_PARTICLE_EFFECTS: "Zimní částicové efekty"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nUrčuje, zda se při aktivním zimním období v některých částech mapy zobrazují částicové efekty.\n\nVypnutí může zvýšit výkon."
 YEARLY: "Každý rok"
 byzantine: "@roadstopower_icon! Cesty k moci"
 default: "Výchozí"
 hud_skin_auto: "Dynamické"
 iberian: "@fateofiberia_icon! Osud Iberie"
 iranian: "@legacyofpersia_icon! Dědictví Persie"
 map_table_style_auto: "Dynamický"
 map_table_style_ce1: "@legendsofthedead_icon! Legendy mrtvých"
 map_table_style_ep3: "@roadstopower_icon! Cesty k moci"
 map_table_style_western: "Výchozí"
 nomad: "@khansofthesteppe_icon! Chánové stepi"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Zvýraznění vrchního pána na mapě"   # todo: NEW TRANSLATION
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nUrčuje, kdy je při výběru království zvýrazněn jeho nejvyšší vrchní pán."   # todo: NEW TRANSLATION
 OPTION_ALWAYS: "Vždy"   # todo: NEW TRANSLATION
 OPTION_TRIBUTARY_ONLY: "Pouze tributáři"   # todo: NEW TRANSLATION
 asia: "@allunderheaven_icon! Vše pod nebem"   # todo: NEW TRANSLATION
 map_table_style_tgp: "@allunderheaven_icon! Vše pod nebem"   # todo: NEW TRANSLATION
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Podrobné ikony [barter|E]"   # todo: NEW TRANSLATION
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nNastavuje, zda by mapové ikony [barter|E] měly zobrazovat zjednodušené nebo podrobné ikony\n\n#I Pokud je povoleno, podržte Alt pro zobrazení všech držeb s kořistí, se kterými můžete [barter|E].#!"   # todo: NEW TRANSLATION
 SETTING_PAPER_MAP_STYLE: "Styl papírové mapy"   # todo: NEW TRANSLATION
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nNastavuje styl mapy zobrazovaný při oddálení.\n\nPokud je vybrána volba $paper_map_style_auto$, papírová mapa bude následovat styl použitý ve \"$SETTING_MAP_TABLE_STYLE$\""."   # todo: NEW TRANSLATION
 paper_map_style_auto: "Dynamický"   # todo: NEW TRANSLATION
 paper_map_style_western: "Výchozí"   # todo: NEW TRANSLATION
 paper_map_style_tgp: "Vše pod nebem"   # todo: NEW TRANSLATION
 SETTING_ADAPTIVE_FRAMERATE: "Adaptivní snímková frekvence"   # todo: NEW TRANSLATION
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Snižuje frekvenci obnovování obrazovky, pokud klesne rychlost aktualizace hry, aby se zlepšil herní výkon."   # todo: NEW TRANSLATION
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Stín mraků"   # todo: NEW TRANSLATION
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nUrčuje, zda se mají na terénu zobrazovat efekty stínů mraků"   # todo: NEW TRANSLATION
 SETTING_HAS_TREE_DITHERING_ENABLED: "Dithering stromů"   # todo: NEW TRANSLATION
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nUrčuje, zda se mají na stromech používat ditheringové efekty ke zjemnění hran"   # todo: NEW TRANSLATION
 SETTING_MAP_BRIGHTNESS: "Jas papírové mapy"   # todo: NEW TRANSLATION
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_BRIGHTNESS$#!\nUrčuje intenzitu jasu papírové mapy"   # todo: NEW TRANSLATION
